"""initial schema

Revision ID: 0f96d778cbde
Revises: 
Create Date: 2026-06-23 21:14:19.547586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f96d778cbde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_predicciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrera_alumno', sa.String(), nullable=False),
    sa.Column('codigo_materia', sa.String(), nullable=False),
    sa.Column('nivel_materia', sa.Integer(), nullable=False),
    sa.Column('repite_materia_binaria', sa.Integer(), nullable=False),
    sa.Column('ppa', sa.Float(), nullable=False),
    sa.Column('ppac', sa.Float(), nullable=False),
    sa.Column('usar_alternativo', sa.Boolean(), nullable=False),
    sa.Column('prediccion', sa.Integer(), nullable=False),
    sa.Column('probabilidad_riesgo', sa.Float(), nullable=False),
    sa.Column('nivel_alerta', sa.String(), nullable=False),
    sa.Column('modelo_utilizado', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos_entrenados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_interno', sa.String(), nullable=False),
    sa.Column('nombre_legible', sa.String(), nullable=False),
    sa.Column('algoritmo', sa.String(), nullable=False),
    sa.Column('configuracion', sa.String(), nullable=False),
    sa.Column('ruta_archivo_pkl', sa.String(), nullable=False),
    sa.Column('es_modelo_final', sa.Boolean(), nullable=False),
    sa.Column('hiperparametros', sa.JSON(), nullable=True),
    sa.Column('entrenado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_interno')
    )
    op.create_index(op.f('ix_modelos_entrenados_es_modelo_final'), 'modelos_entrenados', ['es_modelo_final'], unique=False)
    op.create_table('registros_academicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('carrera_alumno', sa.String(), nullable=False),
    sa.Column('codigo_materia', sa.String(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('nivel_materia', sa.Integer(), nullable=False),
    sa.Column('repite_materia', sa.Integer(), nullable=False),
    sa.Column('repite_materia_binaria', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.Column('ppa', sa.Float(), nullable=False),
    sa.Column('ppac', sa.Float(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('riesgo_academico', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_academicos_carrera_alumno'), 'registros_academicos', ['carrera_alumno'], unique=False)
    op.create_index(op.f('ix_registros_academicos_codigo_materia'), 'registros_academicos', ['codigo_materia'], unique=False)
    op.create_index(op.f('ix_registros_academicos_id_estudiante'), 'registros_academicos', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_registros_academicos_riesgo_academico'), 'registros_academicos', ['riesgo_academico'], unique=False)
    op.create_table('respuestas_encuesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.Column('carrera', sa.String(), nullable=False),
    sa.Column('semestre_num', sa.Integer(), nullable=False),
    sa.Column('promedio_actual_orden', sa.Integer(), nullable=False),
    sa.Column('promedio_actual_estimado', sa.Float(), nullable=False),
    sa.Column('materias_reprobadas_num', sa.Float(), nullable=False),
    sa.Column('horas_estudio_semana_num', sa.Integer(), nullable=False),
    sa.Column('asistencia_ordinal', sa.Integer(), nullable=False),
    sa.Column('frecuencia_uso_ia_ordinal', sa.Integer(), nullable=False),
    sa.Column('dependencia_ia_ordinal', sa.Integer(), nullable=False),
    sa.Column('motivacion_ordinal', sa.Integer(), nullable=False),
    sa.Column('riesgo_academico_encuesta', sa.String(), nullable=False),
    sa.Column('riesgo_academico_encuesta_binario', sa.Integer(), nullable=False),
    sa.Column('frecuencia_uso_ia_desc', sa.String(), nullable=False),
    sa.Column('dependencia_ia_desc', sa.String(), nullable=False),
    sa.Column('motivacion_desc', sa.String(), nullable=False),
    sa.Column('asistencia_desc', sa.String(), nullable=False),
    sa.Column('perfil_uso_ia', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_encuesta')
    )
    op.create_index(op.f('ix_respuestas_encuesta_riesgo_academico_encuesta_binario'), 'respuestas_encuesta', ['riesgo_academico_encuesta_binario'], unique=False)
    op.create_table('evaluaciones_modelo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('accuracy_test', sa.Float(), nullable=True),
    sa.Column('accuracy_train', sa.Float(), nullable=True),
    sa.Column('precision_clase_1', sa.Float(), nullable=True),
    sa.Column('recall_clase_1', sa.Float(), nullable=True),
    sa.Column('recall_train', sa.Float(), nullable=True),
    sa.Column('f1_clase_1', sa.Float(), nullable=True),
    sa.Column('f1_train', sa.Float(), nullable=True),
    sa.Column('roc_auc_test', sa.Float(), nullable=True),
    sa.Column('roc_auc_train', sa.Float(), nullable=True),
    sa.Column('falsos_negativos', sa.Integer(), nullable=True),
    sa.Column('matriz_confusion', sa.JSON(), nullable=True),
    sa.Column('cv_recall_mean', sa.Float(), nullable=True),
    sa.Column('cv_recall_std', sa.Float(), nullable=True),
    sa.Column('classification_report', sa.Text(), nullable=True),
    sa.Column('evaluado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_entrenados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluaciones_modelo')
    op.drop_index(op.f('ix_respuestas_encuesta_riesgo_academico_encuesta_binario'), table_name='respuestas_encuesta')
    op.drop_table('respuestas_encuesta')
    op.drop_index(op.f('ix_registros_academicos_riesgo_academico'), table_name='registros_academicos')
    op.drop_index(op.f('ix_registros_academicos_id_estudiante'), table_name='registros_academicos')
    op.drop_index(op.f('ix_registros_academicos_codigo_materia'), table_name='registros_academicos')
    op.drop_index(op.f('ix_registros_academicos_carrera_alumno'), table_name='registros_academicos')
    op.drop_table('registros_academicos')
    op.drop_index(op.f('ix_modelos_entrenados_es_modelo_final'), table_name='modelos_entrenados')
    op.drop_table('modelos_entrenados')
    op.drop_table('historial_predicciones')
    # ### end Alembic commands ###
